# PeMS04数据集
dataset:
  data_dir: data/pems04
  step_num_in: 12
  step_num_out: 12
  num_nodes: 307
  input_size: 3
  batch_size: 64
  device: cuda:0

AGLNConv:
  num_block: 2
  kernel_size: 5
  num_cheb_filter: 128
  num_time_filter: 128
  conv_type: cheb
  K: 3
  init_feature_num: 64
  # adj_mx_path: model_states/AGLNConv_pems04/best_adj_mx.npy
  # adj_mx_path: model_states/AGLNTogether_pems04/best_adj_mx.npy
  adj_mx_path: model_states/AGLNDivide_pems04/best_adj_mx.npy

AGLNTogether:
  K: 3
  graph_num: 2
  rnn_hidden_size: 128
  rnn_layer_num: 1
  use_gc: True
  batch_first: True
  use_curriculum_learning: True
  cl_decay_steps: 1000
  activation: tanh
  # adj_mx_path: model_states/AGLNConv_pems04/best_adj_mx.npy
  # adj_mx_path: model_states/AGLNTogether_pems04/best_adj_mx.npy
  adj_mx_path: model_states/AGLNDivide_pems04/best_adj_mx.npy
  init_feature_num: 128

AGLNDivide:
  K: 3
  rnn_hidden_size: 64
  rnn_layer_num: 1
  batch_first: True
  conv_type: cheb
  conv_first: False
  with_res: False
  num_block: 2
  num_cheb_filter: 128
  init_feature_num: 128
  # adj_mx_path: model_states/AGLNConv_pems04/best_adj_mx.npy
  # adj_mx_path: model_states/AGLNTogether_pems04/best_adj_mx.npy
  adj_mx_path: model_states/AGLNDivide_pems04/best_adj_mx.npy
